"""create borrowing table

Revision ID: 0e0da6075e7e
Revises: f6311fe67e98
Create Date: 2024-06-19 15:53:05.224832

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e0da6075e7e"
down_revision: Union[str, None] = "f6311fe67e98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "borrowing",
        sa.Column("id", sa.INTEGER, nullable=False, primary_key=True),
        sa.Column("book_id", sa.String, nullable=False),
        sa.Column("user_id", sa.Integer, nullable=False),
        sa.UniqueConstraint("book_id", "user_id", name="uniq_book_id_user_id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("isbn", sa.VARCHAR(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("author", sa.VARCHAR(), nullable=True),
        sa.Column("subject", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("password", sa.VARCHAR(length=256), nullable=True),
        sa.Column("name", sa.VARCHAR(length=50), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("book_id", sa.VARCHAR(), nullable=True),
        sa.Column("count", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["Book.isbn"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id"),
    )
    # ### end Alembic commands ###
